# -*- coding: utf-8 -*-
"""Desafios

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1llVwMCVuR9jE9Fd7UpFnqbaRykN1F-SK
"""

número = int(input("coloque o número do trabalhador: "))
horastrabalhadas = int(input("coloque o número de horas trabalhadas: "))
recebimentoPorHora = int(input("coloque a renda por hora do trabalhador: "))
print("sua renda é",horastrabalhadas*recebimentoPorHora,"por mês")

v = [0,1]
while len(v) <= 50:
  v.append(v[-1]*2)
print(v)

N = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
N.reverse()
print(N)

mêsDoAno = int(input("coloque um número de 1 a 12 aqui: "))

if mêsDoAno == 1:
  print("esse mês é janeiro")
elif mêsDoAno == 2:
  print("esse mês é Feveireiro")
elif mêsDoAno == 3:
  print("esse mês é  Março")
elif mêsDoAno == 4:
  print("esse mês é Abril")
elif mêsDoAno == 5:
  print("esse mês é Maio")
elif mêsDoAno == 6:
  print("esse mês é Junho")
elif mêsDoAno == 7:
  print("esse mês é Julho")
elif mêsDoAno == 8:
  print("esse mês é Agosto")
elif mêsDoAno == 9:
  print("esse mês é Setembro")
elif mêsDoAno == 10:
  print("esse mês é Outubro")
elif mêsDoAno == 11:
  print("esse mês é Novembro")
elif mêsDoAno == 12:
  print("esse mês é Dezembro")
else:
  print("esse número não está entre 1 e 12")

CachorroQuente1 = 4.00
XSalada2 = 4.50
XBacon3 = 5.00
TorradaSimples4 = 2.00
Refrigerante5 = 1.50
Pedido1 = CachorroQuente1
Pedido2 = XSalada2
print("Total:",(Pedido1 + Pedido2),"Reais")

V = int(input("coloque um número menor que 46 aqui: "))
fibonacci = [0,1,1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437,701408733,1134903170]
N = [0]*V
for i in range(0,V):
 N[i]=fibonacci[i]
print(N)

DDD = int(input("coloque o DDD de sua cidade: "))
if DDD == 61:
  print("Você mora em Brasilia")
elif DDD == 71:
  print("Você mora em Salvador")
elif DDD == 11:
  print("Você mora em São Paulo")
elif DDD == 21:
  print("Você mora em Rio de Janeiro")
elif DDD == 32:
  print("Você mora em Juiz de Fora")
elif DDD == 19:
  print("Você mora em Campinas")
elif DDD == 27:
  print("Você mora em Vitória")
elif DDD == 31:
  print("Você mora em Belo Horizonte")
else:
  print("isso não é um DDD cadastrado")

experimento1 = [13, 11, 19],["Rato","Sapo","Coelho"]
experimento2 = [28, 23, 24],["Rato","Sapo","Coelho"]
experimento3 = [34, 41, 17],["Rato","Sapo","Coelho"]
experimento4 = [5, 37, 9],["Rato","Sapo","Coelho"]
dados = input()
def TotalCobaias(experimento):
  print("Total: ",experimento[0][0]+experimento[0][1]+ experimento[0][2]," Cobaias")
def TotalEPorcentagem(animal,Qanimal,experimento):
  print("Total de ",animal,": ",experimento[0][Qanimal])
  print("Porcentagem de ",animal,": ",(experimento[0][Qanimal]*100)/(experimento[0][0]+experimento[0][1]+ experimento[0][2]-experimento[0][Qanimal]),"%")
if dados=="1":
  TotalCobaias(experimento1)
elif dados=="2":
 TotalCobaias(experimento2)
elif dados=="3":
  TotalCobaias(experimento3)
elif dados=="4":
  TotalCobaias(experimento4)
elif dados =="1C":
  TotalEPorcentagem("Coelhos",2,experimento1)
elif dados =="2C":
  TotalEPorcentagem("Coelhos",2,experimento2)
elif dados =="3C":
  TotalEPorcentagem("Coelhos",2,experimento3)
elif dados =="4C":
  TotalEPorcentagem("Coelhos",2,experimento4)
elif dados =="1S":
  TotalEPorcentagem("Sapos",1,experimento1)
elif dados =="2S":
  TotalEPorcentagem("Sapos",1,experimento2)
elif dados =="3S":
  TotalEPorcentagem("Sapos",1,experimento3)
elif dados =="4S":
  TotalEPorcentagem("Sapos",1,experimento4)
elif dados =="1R":
  TotalEPorcentagem("Ratos",0,experimento1)
elif dados =="2R":
  TotalEPorcentagem("Ratos",0,experimento2)
elif dados =="3R":
  TotalEPorcentagem("Ratos",0,experimento3)
elif dados =="4R":
  TotalEPorcentagem("Ratos",0,experimento4)
else:
  print("Isso não é um experimento realizado, tente de novo")

def CidadeEPais(cidade,pais):
  print(cidade," está localizado(a) no(a) ",pais)
CidadeEPais("Madrid","Espanha")

def MaiorABC(a,b,c):
 num1 = (a+b+abs(a-b))/2
 print((num1+c+abs(num1-c))/2)
MaiorABC(67,289,743)

dinheiro = int(input("coloque um número para dividir em cédulas: "))
cédulas100 = 0
cédulas50 = 0
cédulas20 = 0
cédulas10 = 0
cédulas5 = 0
cédulas2 = 0
cédulas1 = 0
def DividirEmCélulas(dinheiroDividido):
  global cédulas100
  global cédulas50
  global cédulas20
  global cédulas10
  global cédulas5
  global cédulas2
  global cédulas1
  while dinheiroDividido >= 100:
    dinheiroDividido = dinheiroDividido - 100
    cédulas100 += 1

  while dinheiroDividido >= 50:
    dinheiroDividido = dinheiroDividido - 50
    cédulas50 += 1
  while dinheiroDividido >= 20:
    dinheiroDividido = dinheiroDividido - 20
    cédulas20 += 1
  while dinheiroDividido >= 10:
    dinheiroDividido = dinheiroDividido - 10
    cédulas10 += 1
  while dinheiroDividido >= 5:
    dinheiroDividido = dinheiroDividido - 5
    cédulas5 += 1
  while dinheiroDividido >= 2:
    dinheiroDividido = dinheiroDividido - 2
    cédulas2 += 1
  while dinheiroDividido >= 1:
    dinheiroDividido = dinheiroDividido - 1
    cédulas1 += 1
  print(cédulas100,"nota(s) de R$","100,00")
  print(cédulas50,"nota(s) de R$","50,00")
  print(cédulas20,"nota(s) de R$","20,00")
  print(cédulas10,"nota(s) de R$","10,00")
  print(cédulas5,"nota(s) de R$","5,00")
  print(cédulas2,"nota(s) de R$","2,00")
  print(cédulas1,"nota(s) de R$","1,00")
DividirEmCélulas(dinheiro)

N = int(input("digite um número de 1 a 100: "))
if N >= 1 and N <= 25:
  print("esse número está entre 1 e 25")
elif N >= 26 and N <= 50:
  print("esse número está entre 25 e 50")
elif N >= 51 and N <= 75:
  print("esse número está entre 50 e 75 ")
elif N >= 76 and N <= 100:
  print("esse número está entre 75 e 100")
else:
  print("esse número não está entre 1 e 100")

InícioDoJogo = int(input("coloque a hora do início do jogo aqui: "))
FimDoJogo = int(input("coloque a hora do fim do jogo aqui: "))
if InícioDoJogo < FimDoJogo:
  print("O jogo durou ",FimDoJogo - InícioDoJogo," Hora(s)")
else:
  print("O jogo durou ",24 - InícioDoJogo + FimDoJogo," Hora(s)")

PrimeiroNúmero = int(input())
SegundoNúmero = int(input())
TerceiroNúmero = int(input())
QuatroNúmero = int(input())
QuintoNúmero = int(input())
N = [PrimeiroNúmero,SegundoNúmero,TerceiroNúmero,QuatroNúmero,QuintoNúmero]
ValoresPares = 0
for i in range(0,5):
 if N[i] % 2 == 0:
  ValoresPares+=1
print(ValoresPares," valores pares")

i = 456
for i in range(i, (i + 12)):
  if i % 2 == 0:
    pass
  else:
      print(i)